/*
    File was generated by CROC jXFW
*/
//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated by a tool.
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
define({
	"model.User": "\u041F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044C",
	"model.User.firstName": "\u0418\u043C\u044F",
	"model.User.lastName": "\u0424\u0430\u043C\u0438\u043B\u0438\u044F",
	"model.User.login": "\u041B\u043E\u0433\u0438\u043D",
	"model.User.role": "\u0420\u043E\u043B\u044C",
	"model.User.avatar": "\u0424\u043E\u0442\u043E",
	"model.User.password": "\u041F\u0430\u0440\u043E\u043B\u044C",
	"model.User.created": "\u0414\u0430\u0442\u0430 \u0441\u043E\u0437\u0434\u0430\u043D\u0438\u044F",
	"model.User.lastLogin": "\u0414\u0430\u0442\u0430 \u043F\u043E\u0441\u043B\u0435\u0434\u043D\u0438\u0435\u0433\u043E \u0432\u0445\u043E\u0434\u0430",
	"model.User.groups": "\u0413\u0440\u0443\u043F\u043F\u044B",
	"model.UserRole": "UserRole",
	"model.UserRole.Admin": "\u0410\u0434\u043C\u0438\u043D\u0438\u0441\u0442\u0440\u0430\u0442\u043E\u0440",
	"model.UserRole.User": "\u041F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044C",
	"model.Group": "\u0413\u0440\u0443\u043F\u043F\u0430",
	"model.Group.name": "\u041D\u0430\u0438\u043C\u0435\u043D\u043E\u0432\u0430\u043D\u0438\u0435",
	"model.Group.users": "\u0427\u043B\u0435\u043D\u044B \u0433\u0440\u0443\u043F\u043F\u044B",
	"model.Group.roles": "\u0420\u043E\u043B\u0438"
});