/*
    File was generated by CROC jXFW
*/
//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated by a tool.
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------
define({
	"model.FilmCompany": "\u041A\u0438\u043D\u043E\u043A\u043E\u043C\u043F\u0430\u043D\u0438\u044F",
	"model.FilmCompany.filmCompany": "\u041A\u0438\u043D\u043E\u043A\u043E\u043C\u043F\u0430\u043D\u0438\u044F",
	"model.Film": "\u0424\u0438\u043B\u044C\u043C",
	"model.Film.filmName": "\u0424\u0438\u043B\u044C\u043C",
	"model.Film.employee": "\u0421\u043E\u0442\u0440\u0443\u0434\u043D\u0438\u043A",
	"model.Film.filmCompany": "\u041A\u0438\u043D\u043E\u043A\u043E\u043C\u043F\u0430\u043D\u0438\u044F",
	"model.Employee": "C\u043E\u0442\u0440\u0443\u0434\u043D\u0438\u043A",
	"model.Employee.firstName": "\u0418\u043C\u044F",
	"model.Employee.lastName": "\u0424\u0430\u043C\u0438\u043B\u0438\u044F",
	"model.Employee.user": "\u041F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044C",
	"model.Employee.fired": "\u0443\u0432\u043E\u043B\u0435\u043D",
	"model.User": "\u041F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044C",
	"model.User.login": "\u041B\u043E\u0433\u0438\u043D",
	"model.User.role": "\u0420\u043E\u043B\u044C",
	"model.User.avatar": "\u0424\u043E\u0442\u043E",
	"model.User.password": "\u041F\u0430\u0440\u043E\u043B\u044C",
	"model.User.created": "\u0414\u0430\u0442\u0430 \u0441\u043E\u0437\u0434\u0430\u043D\u0438\u044F",
	"model.User.lastLogin": "\u0414\u0430\u0442\u0430 \u043F\u043E\u0441\u043B\u0435\u0434\u043D\u0438\u0435\u0433\u043E \u0432\u0445\u043E\u0434\u0430",
	"model.User.groups": "\u0413\u0440\u0443\u043F\u043F\u044B",
	"model.UserRole": "UserRole",
	"model.UserRole.Admin": "\u0410\u0434\u043C\u0438\u043D\u0438\u0441\u0442\u0440\u0430\u0442\u043E\u0440",
	"model.UserRole.User": "\u041F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044C",
	"model.Address": "\u0410\u0434\u0440\u0435\u0441",
	"model.Address.addressName": "\u0430\u0434\u0440\u0435\u0441",
	"model.Address.city": "\u0413\u043E\u0440\u043E\u0434",
	"model.Address.employee": "\u0421\u043E\u0442\u0440\u0443\u0434\u043D\u0438\u043A",
	"model.Post": "\u0414\u043E\u043B\u0436\u043D\u043E\u0441\u0442\u044C",
	"model.Post.postName": "\u041D\u0430\u0437\u0432\u0430\u043D\u0438\u0435 \u0434\u043E\u043B\u0436\u043D\u043E\u0441\u0442\u0438",
	"model.Group": "\u0413\u0440\u0443\u043F\u043F\u0430",
	"model.Group.name": "\u041D\u0430\u0438\u043C\u0435\u043D\u043E\u0432\u0430\u043D\u0438\u0435",
	"model.Group.users": "\u0427\u043B\u0435\u043D\u044B \u0433\u0440\u0443\u043F\u043F\u044B",
	"model.Group.roles": "\u0420\u043E\u043B\u0438",
	"model.Country": "\u0421\u0442\u0440\u0430\u043D\u0430",
	"model.Country.countryName": "\u0421\u0442\u0440\u0430\u043D\u0430",
	"model.Country.city": "\u0413\u043E\u0440\u043E\u0434",
	"model.City": "\u0413\u043E\u0440\u043E\u0434",
	"model.City.cityName": "\u0413\u043E\u0440\u043E\u0434",
	"model.City.country": "\u0421\u0442\u0440\u0430\u043D\u0430",
	"model.City.address": "\u0410\u0434\u0440\u0435\u0441"
});